# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_thing.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1009, 713)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.open_new_synth_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_new_synth_btn.setGeometry(QtCore.QRect(10, 10, 961, 581))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(72)
        self.open_new_synth_btn.setFont(font)
        self.open_new_synth_btn.setObjectName("open_new_synth_btn")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 600, 53, 53))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.channel_chng = QtWidgets.QSpinBox(self.groupBox)
        self.channel_chng.setWrapping(False)
        self.channel_chng.setMaximum(15)
        self.channel_chng.setObjectName("channel_chng")
        self.gridLayout.addWidget(self.channel_chng, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1009, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open_new_synth_btn.setText(_translate("MainWindow", "Ебать синтезатор"))
        self.groupBox.setTitle(_translate("MainWindow", "Channel"))
